---
- hosts: all
  remote_user: root
  become: yes
  become_method: sudo

  roles:
    - role: initialprep 

- hosts: db
  remote_user: root
  become: yes
  become_method: sudo

  roles:
    # using YAML shorthand, this is equivalent to the above:
    - role: database
      when: ansible_facts['os_family'] == 'Debian'

- hosts: web
  remote_user: root
  become: yes
  become_method: sudo

  roles:
    # using YAML shorthand, this is equivalent to the above:
    - role: webserver
      when: ansible_facts['os_family'] == 'Amazon'

